"""Small seed library. Not an indicator zoo. Unsupported categories stay NOT_TESTED."""

from __future__ import annotations

from quantlab.features.definition import (
    FeatureDefinition,
    FeatureFamily,
    FeatureLifecycle,
    FeatureOperator,
    NormalizationMethod,
)


def _ret(lookback: int) -> FeatureDefinition:
    return FeatureDefinition(
        feature_id=f"momentum_{lookback}",
        version="1",
        name=f"Trailing return {lookback} sessions",
        mathematical_definition=f"close[t]/close[t-{lookback}]-1 on PIT-available bars",
        inputs=["close"],
        lookback=lookback,
        operator=FeatureOperator.TRAILING_RETURN,
        family=FeatureFamily.MOMENTUM,
        family_id="trailing_return",
        provenance="seed-library",
        notes="Same formula as MarketState momentum_N / CrossSectionalMomentum",
    )


def seed_library() -> list[FeatureDefinition]:
    features = [
        _ret(1),
        _ret(5),
        _ret(10),
        _ret(20),
        _ret(60),
        _ret(120),
        _ret(252),
        FeatureDefinition(
            feature_id="rolling_mean_20",
            version="1",
            name="Rolling close mean 20",
            mathematical_definition="mean(close[t-19:t])",
            inputs=["close"],
            lookback=20,
            operator=FeatureOperator.ROLLING_MEAN,
            family=FeatureFamily.PRICE,
            family_id="rolling_mean",
        ),
        FeatureDefinition(
            feature_id="rolling_std_20",
            version="1",
            name="Rolling return std 20",
            mathematical_definition="std(simple_return[t-19:t])",
            inputs=["close"],
            lookback=20,
            operator=FeatureOperator.ROLLING_STD,
            family=FeatureFamily.VOLATILITY,
            family_id="rolling_std",
        ),
        FeatureDefinition(
            feature_id="zscore_ts_20",
            version="1",
            name="Trailing close z-score 20",
            mathematical_definition="(close[t]-mean_20)/std_20",
            inputs=["close"],
            lookback=20,
            operator=FeatureOperator.ZSCORE_TS,
            family=FeatureFamily.STATISTICAL,
            family_id="zscore_ts",
            normalization=NormalizationMethod.NONE,
        ),
        FeatureDefinition(
            feature_id="high_low_range",
            version="1",
            name="High-low range",
            mathematical_definition="(high[t]-low[t])/close[t]",
            inputs=["high", "low", "close"],
            lookback=1,
            operator=FeatureOperator.HIGH_LOW_RANGE,
            family=FeatureFamily.MARKET_STRUCTURE,
            family_id="range",
        ),
        FeatureDefinition(
            feature_id="close_to_high",
            version="1",
            name="Close to high",
            mathematical_definition="close[t]/high[t]-1",
            inputs=["close", "high"],
            lookback=1,
            operator=FeatureOperator.CLOSE_TO_HIGH,
            family=FeatureFamily.MARKET_STRUCTURE,
            family_id="close_location",
        ),
        FeatureDefinition(
            feature_id="close_to_low",
            version="1",
            name="Close to low",
            mathematical_definition="close[t]/low[t]-1",
            inputs=["close", "low"],
            lookback=1,
            operator=FeatureOperator.CLOSE_TO_LOW,
            family=FeatureFamily.MARKET_STRUCTURE,
            family_id="close_location",
        ),
        FeatureDefinition(
            feature_id="volume",
            version="1",
            name="Session volume",
            mathematical_definition="volume[t]",
            inputs=["volume"],
            lookback=1,
            operator=FeatureOperator.LAST_VOLUME,
            family=FeatureFamily.VOLUME,
            family_id="volume",
            notes="synthetic volume, not NSE ADV",
        ),
        FeatureDefinition(
            feature_id="volume_change",
            version="1",
            name="Volume change",
            mathematical_definition="volume[t]/volume[t-1]-1",
            inputs=["volume"],
            lookback=1,
            operator=FeatureOperator.VOLUME_CHANGE,
            family=FeatureFamily.VOLUME,
            family_id="volume_change",
            notes="synthetic volume, not NSE ADV",
        ),
        FeatureDefinition(
            feature_id="volume_zscore_20",
            version="1",
            name="Volume z-score 20",
            mathematical_definition="trailing z-score of volume over 20 sessions",
            inputs=["volume"],
            lookback=20,
            operator=FeatureOperator.VOLUME_ZSCORE,
            family=FeatureFamily.VOLUME,
            family_id="volume_zscore",
            notes="synthetic volume, not NSE ADV",
        ),
        FeatureDefinition(
            feature_id="distance_from_mean_20",
            version="1",
            name="Distance from rolling mean",
            mathematical_definition="close[t]/mean(close,20)-1",
            inputs=["close"],
            lookback=20,
            operator=FeatureOperator.DISTANCE_FROM_MEAN,
            family=FeatureFamily.MEAN_REVERSION,
            family_id="distance_from_mean",
        ),
        FeatureDefinition(
            feature_id="dollar_turnover_ratio_20",
            version="1",
            name="Dollar volume vs trailing mean",
            mathematical_definition="(close*volume)/mean(close*volume,20)",
            inputs=["close", "volume"],
            lookback=20,
            operator=FeatureOperator.DOLLAR_TURNOVER_RATIO,
            family=FeatureFamily.LIQUIDITY,
            family_id="turnover_proxy",
            notes="proxy only; shares outstanding not available",
        ),
        FeatureDefinition(
            feature_id="rank_momentum_20",
            version="1",
            name="CS rank of momentum_20",
            mathematical_definition="rank(close[t]/close[t-20]-1) over Universe(T)",
            inputs=["close"],
            lookback=20,
            operator=FeatureOperator.TRAILING_RETURN,
            family=FeatureFamily.CROSS_SECTIONAL,
            family_id="rank_momentum",
            normalization=NormalizationMethod.RANK,
        ),
        FeatureDefinition(
            feature_id="rank_volume",
            version="1",
            name="CS rank of volume",
            mathematical_definition="rank(volume[t]) over Universe(T)",
            inputs=["volume"],
            lookback=1,
            operator=FeatureOperator.LAST_VOLUME,
            family=FeatureFamily.CROSS_SECTIONAL,
            family_id="rank_volume",
            normalization=NormalizationMethod.RANK,
            notes="synthetic volume, not NSE ADV",
        ),
        FeatureDefinition(
            feature_id="rolling_beta_20",
            version="1",
            name="Rolling beta vs market",
            mathematical_definition="NOT_TESTED: Cov(r_i, r_m)/Var(r_m); no bundled index",
            inputs=["close", "market_close"],
            lookback=20,
            operator=FeatureOperator.ROLLING_BETA,
            family=FeatureFamily.RELATIVE,
            family_id="beta",
            lifecycle=FeatureLifecycle.DRAFT,
            notes="NOT_TESTED until a PIT index series is supplied",
        ),
        FeatureDefinition(
            feature_id="sector_membership",
            version="1",
            name="Sector membership",
            mathematical_definition="NOT_TESTED: no PIT sector classification",
            inputs=["sector"],
            lookback=0,
            operator=FeatureOperator.NOT_IMPLEMENTED,
            family=FeatureFamily.RELATIVE,
            family_id="sector",
            lifecycle=FeatureLifecycle.DRAFT,
            notes="NOT_TESTED: no PIT GICS/ICB file",
        ),
        FeatureDefinition(
            feature_id="market_cap_bucket",
            version="1",
            name="Market-cap bucket",
            mathematical_definition="NOT_TESTED: no PIT market cap",
            inputs=["market_cap"],
            lookback=0,
            operator=FeatureOperator.NOT_IMPLEMENTED,
            family=FeatureFamily.LIQUIDITY,
            family_id="size",
            lifecycle=FeatureLifecycle.DRAFT,
            notes="NOT_TESTED: no PIT market-cap history",
        ),
        FeatureDefinition(
            feature_id="adv_liquidity_bucket",
            version="1",
            name="ADV liquidity bucket",
            mathematical_definition="NOT_TESTED: no calibrated NSE ADV",
            inputs=["adv"],
            lookback=0,
            operator=FeatureOperator.NOT_IMPLEMENTED,
            family=FeatureFamily.LIQUIDITY,
            family_id="adv",
            lifecycle=FeatureLifecycle.DRAFT,
            notes="NOT_TESTED: synthetic volume is not NSE ADV",
        ),
    ]
    return features
