"""Seed state variables and regime models. NIFTY and ADV stay NOT_TESTED."""

from __future__ import annotations

from quantlab.regimes.definition import (
    DetectorKind,
    RegimeLifecycle,
    RegimeModel,
    StateVariable,
)


def seed_state_variables() -> list[StateVariable]:
    return [
        StateVariable(
            variable_id="market_ew_return",
            version="1",
            name="Equal-weight universe return",
            mathematical_definition="CS mean of PIT simple close-to-close returns",
            inputs=["close"],
            lookback=1,
            known_limitations="Equal-weight CS proxy; not an official index",
            notes="Do not label this as NIFTY return",
        ),
        StateVariable(
            variable_id="realized_vol_20",
            version="1",
            name="20-session EW realized volatility",
            mathematical_definition="ddof=0 std of last 20 equal-weight universe returns",
            inputs=["market_ew_return"],
            lookback=20,
        ),
        StateVariable(
            variable_id="dispersion_cs",
            version="1",
            name="Cross-sectional return dispersion",
            mathematical_definition="std of PIT simple returns across Universe(T); ddof=0",
            inputs=["close"],
            lookback=1,
        ),
        StateVariable(
            variable_id="breadth_sign",
            version="1",
            name="Sign breadth",
            mathematical_definition="fraction of Universe(T) names with positive simple return",
            inputs=["close"],
            lookback=1,
        ),
        StateVariable(
            variable_id="avg_pairwise_corr",
            version="1",
            name="Average pairwise correlation",
            mathematical_definition="mean off-diagonal of PIT sample correlation of simple returns",
            inputs=["close"],
            lookback=20,
        ),
        StateVariable(
            variable_id="ew_drawdown",
            version="1",
            name="EW wealth drawdown",
            mathematical_definition="peak-to-trough of compounded equal-weight returns through T",
            inputs=["market_ew_return"],
        ),
        StateVariable(
            variable_id="liquidity_adv",
            version="1",
            name="Calibrated ADV",
            mathematical_definition="NOT_TESTED without calibrated NSE ADV",
            inputs=["adv"],
            notes="Synthetic volume is not NSE ADV",
        ),
        StateVariable(
            variable_id="index_nifty_return",
            version="1",
            name="NIFTY return",
            mathematical_definition="NOT_TESTED; official index is not invented",
            inputs=["nifty"],
            notes="Do not fabricate NIFTY",
        ),
    ]


def seed_regime_models() -> list[RegimeModel]:
    return [
        RegimeModel(
            regime_model_id="vol_tercile",
            version="1",
            name="Expanding terciles of EW realized vol",
            detector=DetectorKind.RULE,
            state_features=["realized_vol_20"],
            n_regimes=3,
            labels=["low", "normal", "high"],
            notes="Rule-based description of volatility state. Not a forecast.",
        ),
        RegimeModel(
            regime_model_id="trend_sign",
            version="1",
            name="Sign of 20-session EW return",
            detector=DetectorKind.RULE,
            state_features=["market_ew_return_20"],
            n_regimes=2,
            labels=["down", "up"],
            notes="Trend bucket from trailing EW return. Not a prediction the trend continues.",
        ),
        RegimeModel(
            regime_model_id="vol_trend",
            version="1",
            name="Vol tercile × trend sign",
            detector=DetectorKind.RULE,
            state_features=["realized_vol_20", "market_ew_return_20"],
            n_regimes=6,
            labels=["low_down", "low_up", "normal_down", "normal_up", "high_down", "high_up"],
            notes="Cartesian product of two descriptive buckets. Not alpha.",
        ),
        RegimeModel(
            regime_model_id="corr_tercile",
            version="1",
            name="Expanding terciles of average pairwise correlation",
            detector=DetectorKind.RULE,
            state_features=["avg_pairwise_corr"],
            n_regimes=3,
            labels=["low", "normal", "high"],
        ),
        RegimeModel(
            regime_model_id="hmm_vol_filter",
            version="1",
            name="2-state Gaussian HMM on realized vol (filtered)",
            detector=DetectorKind.HMM_FILTER,
            state_features=["realized_vol_20"],
            n_regimes=2,
            lookback=20,
            min_obs=15,
            parameters={"n_states": 2, "seed": 0, "n_iter": 8},
            labels=["state_0", "state_1"],
            notes="Filtered = information through T. Labels are anonymous; not economic names.",
        ),
        RegimeModel(
            regime_model_id="hmm_vol_smooth",
            version="1",
            name="2-state Gaussian HMM on realized vol (smoothed, retrospective)",
            detector=DetectorKind.HMM_SMOOTH,
            state_features=["realized_vol_20"],
            n_regimes=2,
            lifecycle=RegimeLifecycle.RETROSPECTIVE,
            parameters={"n_states": 2, "seed": 0, "n_iter": 8},
            labels=["state_0", "state_1"],
            notes="Smoothed HMM uses the full sample. Blocked as a predictive/backtest feature.",
        ),
        RegimeModel(
            regime_model_id="cluster_vol_wf",
            version="1",
            name="Walk-forward 2-means on realized vol",
            detector=DetectorKind.CLUSTER_WALK_FORWARD,
            state_features=["realized_vol_20"],
            n_regimes=2,
            parameters={"k": 2, "seed": 0},
            labels=["cluster_0", "cluster_1"],
        ),
        RegimeModel(
            regime_model_id="cluster_vol_full",
            version="1",
            name="Full-sample 2-means (retrospective)",
            detector=DetectorKind.CLUSTER_FULL_SAMPLE,
            state_features=["realized_vol_20"],
            n_regimes=2,
            lifecycle=RegimeLifecycle.RETROSPECTIVE,
            parameters={"k": 2, "seed": 0},
            labels=["cluster_0", "cluster_1"],
            notes="Full-sample clustering is not a historical predictive feature.",
        ),
        RegimeModel(
            regime_model_id="cusum_ew",
            version="1",
            name="CUSUM change-points on EW returns",
            detector=DetectorKind.CHANGE_POINT,
            state_features=["market_ew_return"],
            n_regimes=2,
            parameters={"threshold": 3.0},
            labels=["stable", "shift"],
            notes="A change-point is not a regime. Flag only.",
        ),
    ]
