"""Seed factors. Unsupported categories stay NOT_TESTED. NIFTY is not invented."""

from __future__ import annotations

from quantlab.factors.definition import (
    FactorCategory,
    FactorDefinition,
    FactorLifecycle,
    FactorSource,
)
from quantlab.features.definition import NormalizationMethod


def seed_factors() -> list[FactorDefinition]:
    return [
        FactorDefinition(
            factor_id="market_ew_beta",
            version="1",
            name="Beta vs equal-weight universe",
            category=FactorCategory.MARKET,
            mathematical_definition="Cov(r_i, r_ew)/Var(r_ew) on PIT simple returns",
            economic_intuition="Sensitivity to the research universe, not NIFTY",
            inputs=["close"],
            lookback=20,
            source=FactorSource.EQUAL_WEIGHT_MARKET_BETA,
            normalization=NormalizationMethod.NONE,
            family_id="market",
            lineage={"benchmark": "equal_weight_universe"},
            known_limitations="Equal-weight CS proxy; not an official index",
            notes="Do not label this as NIFTY beta",
        ),
        FactorDefinition(
            factor_id="style_momentum_20",
            version="1",
            name="20-session momentum style",
            category=FactorCategory.STYLE,
            mathematical_definition="rank(momentum_20) over Universe(T)",
            economic_intuition="Winners vs losers; a risk characteristic, not automatic alpha",
            inputs=["momentum_20"],
            lookback=20,
            source=FactorSource.FEATURE,
            feature_id="momentum_20",
            family_id="style_momentum",
            lineage={"feature": "momentum_20@1"},
        ),
        FactorDefinition(
            factor_id="style_reversal_5",
            version="1",
            name="5-session reversal style",
            category=FactorCategory.STYLE,
            mathematical_definition="rank(-momentum_5) over Universe(T)",
            economic_intuition="Short-horizon reversal as a style exposure",
            inputs=["momentum_5"],
            lookback=5,
            source=FactorSource.FEATURE,
            feature_id="momentum_5",
            expected_direction="long_low",
            family_id="style_reversal",
            lineage={"feature": "momentum_5@1"},
        ),
        FactorDefinition(
            factor_id="style_volatility_20",
            version="1",
            name="20-session volatility style",
            category=FactorCategory.VOLATILITY,
            mathematical_definition="rank(rolling_std_20) over Universe(T)",
            economic_intuition="High-vol names as a systematic dimension",
            inputs=["rolling_std_20"],
            lookback=20,
            source=FactorSource.FEATURE,
            feature_id="rolling_std_20",
            family_id="style_vol",
            lineage={"feature": "rolling_std_20@1"},
        ),
        FactorDefinition(
            factor_id="size_log_cap",
            version="1",
            name="Log market cap",
            category=FactorCategory.STYLE,
            mathematical_definition="log(market_cap); NOT_TESTED without PIT cap",
            inputs=["market_cap"],
            source=FactorSource.NOT_IMPLEMENTED,
            lifecycle=FactorLifecycle.NOT_TESTED,
            family_id="size",
            known_limitations="No PIT market-cap history is bundled",
            notes="NOT_TESTED: market cap is not fabricated",
        ),
        FactorDefinition(
            factor_id="value_book_to_market",
            version="1",
            name="Book-to-market",
            category=FactorCategory.STYLE,
            mathematical_definition="book/market; NOT_TESTED without PIT fundamentals",
            inputs=["book_equity", "market_cap"],
            source=FactorSource.NOT_IMPLEMENTED,
            lifecycle=FactorLifecycle.NOT_TESTED,
            family_id="value",
            known_limitations="No PIT book equity is bundled",
            notes="NOT_TESTED: fundamentals are not fabricated",
        ),
        FactorDefinition(
            factor_id="quality_roe",
            version="1",
            name="Return on equity",
            category=FactorCategory.STYLE,
            mathematical_definition="ROE; NOT_TESTED without PIT fundamentals",
            inputs=["net_income", "book_equity"],
            source=FactorSource.NOT_IMPLEMENTED,
            lifecycle=FactorLifecycle.NOT_TESTED,
            family_id="quality",
            notes="NOT_TESTED: fundamentals are not fabricated",
        ),
        FactorDefinition(
            factor_id="liquidity_adv",
            version="1",
            name="Average daily volume",
            category=FactorCategory.LIQUIDITY,
            mathematical_definition="calibrated NSE ADV; NOT_TESTED",
            inputs=["adv"],
            source=FactorSource.NOT_IMPLEMENTED,
            lifecycle=FactorLifecycle.NOT_TESTED,
            family_id="liquidity",
            known_limitations="Synthetic volume is not NSE ADV",
            notes="NOT_TESTED: no calibrated ADV",
        ),
        FactorDefinition(
            factor_id="sector_membership",
            version="1",
            name="Sector membership",
            category=FactorCategory.SECTOR,
            mathematical_definition="PIT sector dummy; NOT_TESTED",
            inputs=["sector"],
            source=FactorSource.NOT_IMPLEMENTED,
            lifecycle=FactorLifecycle.NOT_TESTED,
            family_id="sector",
            known_limitations="No PIT GICS/ICB file",
            notes="NOT_TESTED: today's sector map is not used historically",
        ),
    ]
